# Numpy 学习笔记
大纲：
NumPy 是什么
NumPy arrays（1D / 2D / 3D，axis 的概念）
Creating Arrays（创建数组）
Inspecting Your Array（查看数组属性）
Subsetting / Slicing / Indexing（索引切片）
Array Math（运算）
Aggregate Functions（聚合）
Array Manipulation（变形、拼接、拆分）
Copying / Sorting / I/O / Data Types

## 第1章：NumPy 
### 第一步：认识Numpy
NumPy 是 Python 科学计算的核心库，提供了高性能的多维数组对象，以及对这些数组进行操作的工具。
可以理解为：
    比 Python 原生 list 更适合做数值计算
    支持一维、二维、三维甚至更多维的数据
    支持“整体运算”，不需要总是自己写 for 循环
导入时通常写成：

In [1]:
import numpy as np

### 第二步：什么是数组 
    1D array：一维数组，像一行数字
    2D array：二维数组，像表格
    3D array：三维数组，像很多层表格叠起来
axis：坐标轴

In [2]:
#一维数组
a = np.array([1, 2, 3, 4, 5])
#二维数组
b = np.array([[1, 2, 3], [4, 5, 6]])
#三维数组
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]])
print("一维数组：\n", a)
print("二维数组：\n", b)
print("三维数组：\n", c)

一维数组：
 [1 2 3 4 5]
二维数组：
 [[1 2 3]
 [4 5 6]]
三维数组：
 [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


### 第三步: axis 
    axis=0：沿着“行的方向”往下看，表示“按列处理”
    axis=1：沿着“列的方向”往右看，表示“按行处理”

In [3]:
#每一列的最大值
print("每一列的最大值：\n", b.max(axis=0))

每一列的最大值：
 [4 5 6]


## 第二章 Creating Arrays

### 从列表创建数组 


In [4]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)#指定数据类型为float

print(a)
print(b)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


### 创建特殊数组

In [5]:
z = np.zeros((3, 4))#创建一个3行4列的全零数组
print(z)
o = np.ones((2, 3, 4), dtype=np.int16)#创建一个2行3列4层的全一数组，数据类型为16位整数
print(o)
e = np.empty((2, 3))#创建一个2行3列的空数组，数组中的值是未初始化的随机值
print(e)
f = np.full((2, 2), 7)#创建一个2行2列的数组，所有元素的值为7
print(f)
i = np.eye(3)#创建一个3行3列的单位矩阵
print(i) 
d = np.arange(10, 30, 5)#创建一个从10到30（不包括30），步长为5的一维数组
print(d)
l = np.linspace(0, 2, 9)#创建一个从0到2（包括2），等间隔的9个数的一维数组
print(l)
r = np.random.random((2, 3))#创建一个2行3列的数组，数组中的值是0到1之间的随机数
print(r)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[10 15 20 25]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[[0.51318242 0.02067444 0.2127252 ]
 [0.26308451 0.27555959 0.17296839]]


### 查看数组属性
维数、形状、元素个数、元素类型
Numpy与python一个很大的区别就是numpy数组通常要求元素类型统一

In [6]:
print("数组的形状：", b.shape)
print("数组第一维长度：", b.shape[0])
print("数组第一维长度：", len(b))
print("数组的维数：", a.ndim,b.ndim,c.ndim)
print("数组元素总数：", a.size,b.size,c.size)
print("数组元素的数据类型：", a.dtype,b.dtype,c.dtype)
print("数据类型名字字符串：", b.dtype.name)
print(b)
print(b.astype(int))#将数组b的数据类型转换为整数类型


数组的形状： (2, 3)
数组第一维长度： 2
数组第一维长度： 2
数组的维数： 1 2 3
数组元素总数： 3 6 12
数组元素的数据类型： int64 float64 float64
数据类型名字字符串： float64
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1 2 3]
 [4 5 6]]


## 切片与索引 (Slicing and Indexing)

In [7]:
#一维数组切片[]左闭右开
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("原数组:", a)
print("a[2:7] =", a[2:7])
print("a[::2] =", a[::2])
print("a[::-1] =", a[::-1])#反向切片

原数组: [1 2 3 4 5 6 7 8 9]
a[2:7] = [3 4 5 6 7]
a[::2] = [1 3 5 7 9]
a[::-1] = [9 8 7 6 5 4 3 2 1]


In [8]:
#多维数组切片
print(b[0:2, 1])#第0行和第1行，第一列
print(b[:1])#第一列
print(b[0])
print(c[1, ...])
print(c[1, :, :])


[2. 5.]
[[1.5 2.  3. ]]
[1.5 2.  3. ]
[[3. 2. 1.]
 [4. 5. 6.]]
[[3. 2. 1.]
 [4. 5. 6.]]


b[0] 和 b[0:1] 不一样
b[0]：降成一维
b[0:1]：仍然保持二维
...表示后面所有维数都保留

In [9]:
# 布尔索引:条件索引
print(a[a<2])
print(a[a >= 2]) 
print(a[a != 2])
print(b[b > 2])

[1]
[2 3 4 5 6 7 8 9]
[1 3 4 5 6 7 8 9]
[3. 4. 5. 6.]


布尔索引对二维也适用，但是结果会变成一维

In [10]:
#Fancy Indexing：指定下标取多个元素
print(b[[1, 0, 1, 0], 
[0, 1, 2, 0]])
print(b[[1, 0, 1, 0]][:, [0, 1, 2, 0]])#先选一些行，再选一些列，得到一个更大的子矩阵

[4.  2.  6.  1.5]
[[4.  5.  6.  4. ]
 [1.5 2.  3.  1.5]
 [4.  5.  6.  4. ]
 [1.5 2.  3.  1.5]]


## 数组运算
不需要一个元素一个元素做循环，直接对整个数组做运算

In [11]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([
    [1.5, 2, 3],
    [4, 5, 6]
])
#数组的加法
print("数组的加法：\n", a + b)
#数组的减法
print("数组的减法：\n", a - b) 
#数组的乘法
print("数组的乘法：\n", a * b)
print(np.multiply(a, b))
#数组的除法
print("数组的除法：\n", a / b)
#指数运算
print("数组的指数运算：\n", np.exp(a))
#平方根
print("数组的平方根：\n", np.sqrt(a))  
#三角函数     默认弧度制
print("数组的三角函数：\n", np.sin(a))
print("数组的余弦函数：\n", np.cos(a))
#对数运算
print("数组的对数运算：\n", np.log(a))
#点积
print("数组的点积：\n", a.dot(b.T))#a和b的转置的点积

数组的加法：
 [[ 2.5  4.   6. ]
 [ 8.  10.  12. ]]
数组的减法：
 [[-0.5  0.   0. ]
 [ 0.   0.   0. ]]
数组的乘法：
 [[ 1.5  4.   9. ]
 [16.  25.  36. ]]
[[ 1.5  4.   9. ]
 [16.  25.  36. ]]
数组的除法：
 [[0.66666667 1.         1.        ]
 [1.         1.         1.        ]]
数组的指数运算：
 [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
数组的平方根：
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
数组的三角函数：
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
数组的余弦函数：
 [[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
数组的对数运算：
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
数组的点积：
 [[14.5 32. ]
 [34.  77. ]]


这里的运算都是按元素逐项运算，两个数组shape一样通常就能运算。
点积遵循线性代数乘法

数组与标量也能运算

In [12]:
print(a + 10)#数组的加法，数组中的每个元素都加上10
print(a * 2)#数组的乘法，数组中的每个元素都乘以2
print(a / 2)#数组的除法，数组中的每个元素都除以2

[[11 12 13]
 [14 15 16]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


### 聚合函数

In [13]:
#求和
print("数组的求和：\n", a.sum())#数组所有元素的和
print("数组每列的求和：\n", a.sum(axis=0))#数组每列的和
print("数组每行的求和：\n", a.sum(axis=1))#数组每行的和

数组的求和：
 21
数组每列的求和：
 [5 7 9]
数组每行的求和：
 [ 6 15]


In [14]:
#最小值
print("数组的最小值：\n", a.min())#数组所有元素的最小值
print("数组每列的最小值：\n", a.min(axis=0))    #数组每列的最小值
print("数组每行的最小值：\n", a.min(axis=1))    #数组每行的最小值
#最大值
print("数组的最大值：\n", a.max())#数组所有元素的最大值
print("数组每列的最大值：\n", a.max(axis=0))    #数组每列的最大值
print("数组每行的最大值：\n", a.max(axis=1))    #数组每行的最大值

数组的最小值：
 1
数组每列的最小值：
 [1 2 3]
数组每行的最小值：
 [1 4]
数组的最大值：
 6
数组每列的最大值：
 [4 5 6]
数组每行的最大值：
 [3 6]


In [15]:
#平均值
print("数组的平均值：\n", a.mean())#数组所有元素的平均值
print("数组每列的平均值：\n", a.mean(axis=0))    #数组每列的平均值
print("数组每行的平均值：\n", a.mean(axis=1))    #数组每行的平均值

数组的平均值：
 3.5
数组每列的平均值：
 [2.5 3.5 4.5]
数组每行的平均值：
 [2. 5.]


In [16]:
#累计和
print(a)
print("数组的累计和：\n", a.cumsum())#数组所有元素的累计和
print("数组每列的累计和：\n", a.cumsum(axis=0))#数组每列的累计和
print("数组每行的累计和：\n", a.cumsum(axis=1))#数组每行的累计和

[[1 2 3]
 [4 5 6]]
数组的累计和：
 [ 1  3  6 10 15 21]
数组每列的累计和：
 [[1 2 3]
 [5 7 9]]
数组每行的累计和：
 [[ 1  3  6]
 [ 4  9 15]]


In [17]:
#中位数
print("数组的中位数：\n", np.median(a))#数组所有元素的中位数
#标准差
print("数组的标准差：\n", a.std())#数组所有元素的标准差（也可以按轴算）
#相关系数
print("数组的相关系数：\n", np.corrcoef(a, b[0]))#数组a和b的第一行的相关系数

数组的中位数：
 3.5
数组的标准差：
 1.707825127659933
数组的相关系数：
 [[1.         1.         0.98198051]
 [1.         1.         0.98198051]
 [0.98198051 0.98198051 1.        ]]


### 数组操作

In [18]:
a = np.array([1, 2, 3])

b = np.array([
    [1.5, 2, 3],
    [4, 5, 6]
])

e = np.full((2, 2), 7)

f = np.eye(2)

In [19]:
#转置
print("数组b的转置：\n", b.T)

数组b的转置：
 [[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]


In [20]:
#展平
print("数组b的展平：\n", b.flatten())
print("数组b的展平：\n", b.ravel())#与flatten类似，但返回的是视图而不是副本

数组b的展平：
 [1.5 2.  3.  4.  5.  6. ]
数组b的展平：
 [1.5 2.  3.  4.  5.  6. ]


In [21]:
#变形
print("数组b的变形\n", b.reshape(3, 2))#将数组b变形为3行2列的数组
print(b.reshape(3, -1).reshape(2, -1))#将数组b变形为3行2列的数组，再变形为2行3列的数组   numpy会自动计算出-1的值，使得变形后的数组的元素总数不变
x = np.array([1, 2, 3, 4, 5, 6])
x.resize(3, 2)#将数组x变形为3行2列的数组，resize会修改原数组，而reshape不会修改原数组
print(x)

数组b的变形
 [[1.5 2. ]
 [3.  4. ]
 [5.  6. ]]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1 2]
 [3 4]
 [5 6]]


In [22]:
#追加元素
c = np.append(a, [4, 5])
print(c)
print(a)

[1 2 3 4 5]
[1 2 3]


append会默认返回一个新数组，不会修改原数组

In [23]:
#插入元素
print(np.insert(a, 2, [10, 11]))#在数组a的第2个位置插入10和11，原数组不变
#删除元素
print(np.delete(a, 2))#删除数组a的第2个元素，原数组不变
#拼接数组
print(np.concatenate((a, a)))#将数组a和数组a拼接成一个新的数组
print(np.vstack((a, a)))#将数组a和数组a在垂直方向上拼接成一个新的数组
print(np.hstack((e, f)))#将数组e和数组f在水平方向上拼接成一个新的数组

#按列拼接
d = np.array([7, 8, 9])
print(np.column_stack((a, d)))
print(np.c_[a, d])#与column_stack类似，但更简洁

#快捷拼接
print(np.r_[a, d])#将数组a和数组d在垂直方向上拼接成一个新的数组
print(np.c_[a, d])#将数组a和数组d在水平方向上拼接成一个新的数组


[ 1  2 10 11  3]
[1 2]
[1 2 3 1 2 3]
[[1 2 3]
 [1 2 3]]
[[7. 7. 1. 0.]
 [7. 7. 0. 1.]]
[[1 7]
 [2 8]
 [3 9]]
[[1 7]
 [2 8]
 [3 9]]
[1 2 3 7 8 9]
[[1 7]
 [2 8]
 [3 9]]


In [24]:
#拆分数组
print(np.split(a, 3))#将数组a拆分成3个子数组
print(np.hsplit(b, 3))#将数组b在水平方向上拆分成3个子数组

[array([1]), array([2]), array([3])]
[array([[1.5],
       [4. ]]), array([[2.],
       [5.]]), array([[3.],
       [6.]])]


## 操作

### 数组比较

In [25]:
#元素比较
a = np.array([1, 2, 3])
b = np.array([1, 5, 3])
print(a == b)#比较数组a和数组b的元素是否相等，返回一个布尔数组

[ True False  True]


In [26]:
#和标量比较
print(a < 2)#比较数组a的元素是否小于2，返回一个布尔数组

[ True False False]


In [27]:
#整个数组是否相同
c = np.array([1, 2, 3])
print(np.array_equal(a, c))#比较数组a和数组c是否相同，
print(np.array_equal(a, b))#比较数组a和数组b是否相同

True
False


### 数组复制

In [28]:
#浅层视图view
h = a.view()#创建一个数组a的浅层视图，h和a共享数据，但h和a是不同的对象
h[0] = 10
print(h)
print(a)

[10  2  3]
[10  2  3]


In [29]:
#深拷贝copy
i = a.copy()#创建一个数组a的深拷贝，i和a不共享数据，i和a是不同的对象
i[0] = 20   
print(i)
print(a)

[20  2  3]
[10  2  3]


### 数组排序

In [31]:
#一维数组排序
a = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print(np.sort(a))#返回一个新的数组，原数组不变
print(a)
a.sort()#对数组a进行排序，原数组被修改
print(a)

[1 1 2 3 4 5 6 9]
[3 1 4 1 5 9 2 6]
[1 1 2 3 4 5 6 9]


In [32]:
#二维数组按轴排序
x= np.array([[3, 2, 1], [6, 5, 4]])
x.sort(axis=0)#按列排序
print(x)
x.sort(axis=1)#按行排序
print(x)

[[3 2 1]
 [6 5 4]]
[[1 2 3]
 [4 5 6]]


### 数据读写

In [ ]:
#文本文件读写
np.savetxt('array.txt', a, fmt='%d')#将数组a保存到文本文件array.txt中，fmt指定保存的格式为整数
b = np.loadtxt('array.txt', dtype=int)#从文本文件array.txt中加载数据，dtype指定加载的数据类型为整数
np.genfromtxt('array.txt', dtype=int)#从文本文件array.txt中加载数据，dtype指定加载的数据类型为整数，genfromtxt比loadtxt更灵活，可以处理缺失数据等情况   


In [ ]:
#二进制保存
np.save('array.npy', a)#将数组a保存到二进制文件array.npy中
np.savez('arrays.npz', a=a, b=b)#将数组a和数组b保存到一个压缩的二进制文件arrays.npz中，savez会将多个数组保存到一个文件中，并且可以通过关键字参数来指定每个数组的名字
data = np.load('array.npy')#从二进制文件array.npy中加载数据
print(data)
data = np.load('arrays.npz')#从压缩的二进制文件arrays.npz中加载数据
print(data['a'])#访问保存的数组a

### 数据类型

In [ ]:
np.int64#64位整数类型
np.float32#32位浮点数类型
np.complex128#复数类型，128位复数由两个64位浮点数组成，分别表示实部和虚部
np.bool#布尔类型
np.object_#对象类型
np.string_#字符串类型
np.unicode_#Unicode字符串类型
#字符串转换
b.astype(str)


### 查看帮助

In [33]:
np.info(np.ndarray)


 ndarray(shape, dtype=None, buffer=None, offset=0, strides=None, order=None)

ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
    Default is `numpy.float64`.
bu